.PHONY: clean

all: test

test:
	bash ./test_crypt_lib.sh

clean:
	rm alice_private_key_py.pem
	rm alice_public_key_py.pem
	
	rm bob_private_key_py.pem
	rm bob_public_key_py.pem

	rm example_cyphertext_py.json
	rm example_output_py.json


	rm alice_private_key_js.pem
	rm alice_public_key_js.pem

	rm bob_private_key_js.pem
	rm bob_public_key_js.pem

	rm example_cyphertext_js.json
	rm example_output_js.json


	rm charlie_private_key.pem
	rm charlie_public_key.pem

	rm dave_private_key.pem
	rm dave_public_key.pem

	rm example_cyphertext_py_2.json
	rm example_output_py_2.json


	rm ethan_private_key.pem
	rm ethan_public_key.pem

	rm frank_private_key.pem
	rm frank_public_key.pem

	rm example_cyphertext_js_2.json
	rm example_output_js_2.json

